/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto.poo;

import java.awt.Color;

/**
 *
 * @author JOSUE CORDOVA
 */
public class frm_Loggin extends javax.swing.JFrame {

    int mouseX, mouseY;

    public frm_Loggin() {
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_fondo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        pnl_ingresar = new javax.swing.JPanel();
        lbl_ingresar = new javax.swing.JLabel();
        pnl_head = new javax.swing.JPanel();
        pnl_cerrar = new javax.swing.JPanel();
        lbl_cerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        pnl_fondo.setBackground(new java.awt.Color(255, 255, 255));
        pnl_fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("UNIVERSITARIA");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl_fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, 50));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BIBLIOTECA ");
        pnl_fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 160, 50));

        jLabel2.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://raw.githubusercontent.com/AnthonyZabs/SimpleJavaLoginMD/main/src/com/images/logo.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        pnl_fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 150, 140));

        jLabel1.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://raw.githubusercontent.com/AnthonyZabs/SimpleJavaLoginMD/main/src/com/images/city.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        pnl_fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 270, 500));

        txt_user.setText("Ingrese su codigo de usuario");
        txt_user.setBorder(null);
        txt_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_userMousePressed(evt);
            }
        });
        pnl_fondo.add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 290, 40));

        txt_pass.setText("**************");
        txt_pass.setBorder(null);
        txt_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_passMousePressed(evt);
            }
        });
        pnl_fondo.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 290, 40));

        jLabel5.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel5.setText("INICIO DE SESION");
        pnl_fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 230, 60));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel6.setText("CONTRASEÑA");
        pnl_fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 110, 30));

        jLabel7.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel7.setText("USUARIO");
        pnl_fondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 80, 30));
        pnl_fondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 290, 20));
        pnl_fondo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 290, 20));

        pnl_ingresar.setBackground(new java.awt.Color(0, 134, 190));
        pnl_ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_ingresarMouseClicked(evt);
            }
        });

        lbl_ingresar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lbl_ingresar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ingresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ingresar.setText("INGRESAR");
        lbl_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ingresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ingresarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_ingresarLayout = new javax.swing.GroupLayout(pnl_ingresar);
        pnl_ingresar.setLayout(pnl_ingresarLayout);
        pnl_ingresarLayout.setHorizontalGroup(
            pnl_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ingresarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_ingresar, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_ingresarLayout.setVerticalGroup(
            pnl_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ingresarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_ingresar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_fondo.add(pnl_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 110, 40));

        pnl_head.setBackground(new java.awt.Color(255, 255, 255));
        pnl_head.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_headMouseDragged(evt);
            }
        });
        pnl_head.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_headMousePressed(evt);
            }
        });

        pnl_cerrar.setBackground(new java.awt.Color(255, 255, 255));
        pnl_cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_cerrarMouseExited(evt);
            }
        });

        lbl_cerrar.setBackground(new java.awt.Color(255, 255, 255));
        lbl_cerrar.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lbl_cerrar.setForeground(new java.awt.Color(51, 51, 51));
        lbl_cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cerrar.setText("X");
        lbl_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnl_cerrarLayout = new javax.swing.GroupLayout(pnl_cerrar);
        pnl_cerrar.setLayout(pnl_cerrarLayout);
        pnl_cerrarLayout.setHorizontalGroup(
            pnl_cerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        pnl_cerrarLayout.setVerticalGroup(
            pnl_cerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_cerrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnl_headLayout = new javax.swing.GroupLayout(pnl_head);
        pnl_head.setLayout(pnl_headLayout);
        pnl_headLayout.setHorizontalGroup(
            pnl_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_headLayout.createSequentialGroup()
                .addComponent(pnl_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 680, Short.MAX_VALUE))
        );
        pnl_headLayout.setVerticalGroup(
            pnl_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_headLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnl_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl_fondo.add(pnl_head, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_cerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_pnl_cerrarMouseClicked

    private void pnl_headMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_headMousePressed
        mouseX= evt.getX();
        mouseY= evt.getY();
    }//GEN-LAST:event_pnl_headMousePressed

    private void pnl_headMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_headMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();      
        this.setLocation(x-mouseX, y - mouseY);
    }//GEN-LAST:event_pnl_headMouseDragged

    private void pnl_cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_cerrarMouseEntered
        pnl_cerrar.setBackground(Color.red);
    }//GEN-LAST:event_pnl_cerrarMouseEntered

    private void pnl_cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_cerrarMouseExited
        pnl_cerrar.setBackground(Color.white);
    }//GEN-LAST:event_pnl_cerrarMouseExited

    private void lbl_ingresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ingresarMouseEntered
        pnl_ingresar.setBackground(new Color(0,150,223));
    }//GEN-LAST:event_lbl_ingresarMouseEntered

    private void lbl_ingresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ingresarMouseExited
        pnl_ingresar.setBackground(new Color(0,134,190));
    }//GEN-LAST:event_lbl_ingresarMouseExited

    private void txt_userMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_userMousePressed
        if(txt_user.getText().equals("Ingrese su codigo de usuario")){
            txt_user.setText("");
            txt_user.setForeground(Color.black);
        }
        if(String.valueOf(txt_pass.getPassword()).isEmpty()){
            txt_pass.setText("**************");
            txt_pass.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txt_userMousePressed

    private void txt_passMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_passMousePressed
        
        if(String.valueOf(txt_pass.getPassword()).equals("**************")){
            txt_pass.setText("");
            txt_pass.setForeground(Color.black);
        }
        if(txt_user.getText().isEmpty()){
            txt_user.setText("Ingrese su codigo de usuario");
            txt_user.setForeground(Color.gray);
            
        }
    }//GEN-LAST:event_txt_passMousePressed

    private void pnl_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_ingresarMouseClicked
        System.out.println("INGRESAR");
    }//GEN-LAST:event_pnl_ingresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Loggin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_cerrar;
    private javax.swing.JLabel lbl_ingresar;
    private javax.swing.JPanel pnl_cerrar;
    private javax.swing.JPanel pnl_fondo;
    private javax.swing.JPanel pnl_head;
    private javax.swing.JPanel pnl_ingresar;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
